### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Butane973** [Unprotesting/Auto-Tune#11]
Latest plugin auto-tune-0.12.1.jar
Latest versions of Vault and Ultimate-Economy installed & working

`[27.12 17:08:38] [Server] [Server thread/INFO]: [[AUTO-TUNE]] Enabling Auto-Tune v0.12.1
[27.12 17:08:38] [Server] [Server thread/ERROR]: Disabled Auto-Tune due to no Vault dependency found! Please make sure Vault and another economy plugin, such as EssentialsX is installed!
[27.12 17:08:38] [Server] [Server thread/INFO]: [[AUTO-TUNE]] Disabling Auto-Tune v0.12.1
[27.12 17:08:38] [Server] [Server thread/ERROR]: Error occurred while disabling Auto-Tune v0.12.1 (Is it up to date?)
[27.12 17:08:38] [Server] java.lang.NullPointerExceptionnull
[27.12 17:08:38] [Server] 	at unprotesting.com.github.Main.closeDataFiles(Main.java:483) ~[?:?]
[27.12 17:08:38] [Server] 	at unprotesting.com.github.Main.onDisable(Main.java:189) ~[?:?]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at unprotesting.com.github.Main.onEnable(Main.java:209) ~[?:?]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
[27.12 17:08:38] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]`

**Comment by Unprotesting** [comment]
Plugin list apart from Vault/Ultimate Economy?

**Comment by Butane973** [comment]
Multiverse, Luckyperms, ProtocoLib, holographicdisplays, deluxemenus, worldedit and worldgaurd
