### ISSUE TITLE
/ at command in the console prints an error 

### ISSUE THREAD

**Issue by Uranusak** [Unprotesting/Auto-Tune#12]
server: git-Paper-445 (MC: 1.16.5)
auto-tune: owns the latest build from github 

at command in the console prints an error 

```
at
[10:51:19 WARN]: Unexpected exception while parsing console command "at"
org.bukkit.command.CommandException: Unhandled exception executing command 'at' in plugin Auto-Tune v0.13.0-pre-release-3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-445]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at unprotesting.com.github.Commands.AutoTuneCommand.onCommand(AutoTuneCommand.java:27) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-445]
        ... 9 more

```

**Comment by Unprotesting** [comment]
This isn't a bug its just that /at isn't supported in the console, its also not the most important command, most of the config and monitoring is done within the config.yml file. I'll work on sorting the error and then on making it work in console
