### ISSUE TITLE
Requesting 1.20.4 support

### ISSUE THREAD

**Issue by Faeest** [Unprotesting/Auto-Tune#131]
I wonder if the plugin will suppport 1.20.4 soon or not. thanks

**Comment by Faeest** [comment]
for context, I got this error when I put it on my paper 1.20.4 server : 
java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.xxhash.XXHash32JavaSafe
	at net.jpountz.xxhash.XXHashFactory.instance(XXHashFactory.java:49) ~[Auto-Tune-0.14.4.jar:?]
	at net.jpountz.xxhash.XXHashFactory.safeInstance(XXHashFactory.java:85) ~[Auto-Tune-0.14.4.jar:?]
	at net.jpountz.xxhash.XXHashFactory.fastestJavaInstance(XXHashFactory.java:111) ~[Auto-Tune-0.14.4.jar:?]
	at net.jpountz.xxhash.XXHashFactory.fastestInstance(XXHashFactory.java:137) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.mapdb.CC.<clinit>(CC.java:47) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.mapdb.serializer.SerializerByteArray.<clinit>(SerializerByteArray.java:15) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.mapdb.Serializer.<clinit>(Serializer.java:315) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.mapdb.DB.<clinit>(DB.kt:45) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.mapdb.DBMaker$Maker.make(DBMaker.kt:490) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.data.Database.createDb(Database.java:201) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.data.Database.<init>(Database.java:59) ~[Auto-Tune-0.14.4.jar:?]
	at unprotesting.com.github.AutoTune.onEnable(AutoTune.java:38) ~[Auto-Tune-0.14.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-493]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-493]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-493]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.jpountz.xxhash.XXHash32JavaSafe
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.jpountz.xxhash.XXHashFactory.classInstance(XXHashFactory.java:143) ~[Auto-Tune-0.14.4.jar:?]
	at net.jpountz.xxhash.XXHashFactory.<init>(XXHashFactory.java:156) ~[Auto-Tune-0.14.4.jar:?]
	at net.jpountz.xxhash.XXHashFactory.instance(XXHashFactory.java:47) ~[Auto-Tune-0.14.4.jar:?]
	... 23 more
[09:28:39] [Server thread/INFO]: [Auto-Tune] Disabling Auto-Tune v0.14.3
[09:28:39] [Server thread/INFO]: [Auto-Tune] [WARNING] Database is already closed.
[09:28:39] [Server thread/INFO]: [Auto-Tune] Auto-Tune is now disabled!

**Comment by noahbclarkson** [comment]
1.20.4 support request — Auto-Tune now targets Paper 1.21.4 on rewrite-2.
