### ISSUE TITLE
[BUG] Error when using command from console

### ISSUE THREAD

**Issue by rafaelfaustini** [Unprotesting/Auto-Tune#21]
**Describe the bug**
Console throws an error when executing the command
**To Reproduce**
1. Go to the console
2.  Write gdp
3. Console will throw an exception due invalid casting for player (Since it's the console sending the command, and the command probably only expects a player)

**Expected behavior**
Show the info just for the console (Just like any other plugin)

**Screenshots**
![image](https://user-images.githubusercontent.com/26970976/111853358-72d92600-88f9-11eb-9596-5cf34f51a371.png)
```
org.bukkit.command.CommandException: Unhandled exception executing command 'gdp' in plugin Auto-Tune v0.12.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:413) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:380) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at unprotesting.com.github.Commands.AutoTuneGDPCommand.onCommand(AutoTuneGDPCommand.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-545]
        ... 9 more
````

**Minecraft Server Version
1.16.4

**Plugin List
Essentials, Vault, WorldEdit, Terra, FreeRPG

**Comment by rafaelfaustini** [comment]
Error could be avoid with 
```java
if(sender instanceof Player){
 // Casting etc
} else {
 // Console (could be adapted for console or just send a message of error without throwing an exception)
}
````
Before casting to `Player` type

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
