### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by valenvaio** [Unprotesting/Auto-Tune#22]
[08:39:23 INFO]: Fandorin issued server command: /at decrease Prismarin 30
[08:39:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'at' in plugin Auto-Tune v0.13.0-pre-release-4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[mainsrv.jar:git-Purpur-1042]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[mainsrv.jar:git-Purpur-1042]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2286) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2101) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2054) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[mainsrv.jar:git-Purpur-1042]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[mainsrv.jar:git-Purpur-1042]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "price" is null
        at unprotesting.com.github.util.InflationEventHandler.decreaseItemPrice(InflationEventHandler.java:44) ~[?:?]
        at unprotesting.com.github.Commands.AutoTuneCommand.onCommand(AutoTuneCommand.java:124) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[mainsrv.jar:git-Purpur-1042]
        ... 19 more

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
