### ISSUE TITLE
I deactivate max sell and max buy  bug

### ISSUE THREAD

**Issue by titi49600** [Unprotesting/Auto-Tune#24]
hello I report a bug when I deactivate max sell and max buy I can no longer buy but open the menu
```
[21:38:48] [Server thread/ERROR]: [[AUTO-TUNE]] Exception while handling click event in inventory 'Shop', slot=10, item=EMERALD_ORE
java.lang.NullPointerException: null
	at unprotesting.com.github.Commands.AutoTuneGUIShopUserCommand.lambda$4(AutoTuneGUIShopUserCommand.java:251) ~[?:?]
	at com.github.stefvanschie.inventoryframework.GuiItem.callAction(GuiItem.java:134) ~[?:?]
	at com.github.stefvanschie.inventoryframework.pane.OutlinePane.click(OutlinePane.java:244) ~[?:?]
	at com.github.stefvanschie.inventoryframework.GuiListener.onInventoryClick(GuiListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor393.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-189]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-189]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-189]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

thank

**Comment by Ryoyo2** [comment]
This is a bug that seems to have been fixed in a newer version that is not on github yet. It is however on the authors discord. I would give that a try and report back if it doesn't work.

Invite to discord: https://discord.com/invite/bNVVPe5
Link to jar: https://discord.com/channels/748222485975269508/748222912565215303/814267144023048243

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
