### ISSUE TITLE
[BUG] Plugin doesn't even load. 

### ISSUE THREAD

**Issue by Justusbr0405** [Unprotesting/Auto-Tune#86]
**Describe the bug**
Plugin autotune latest version refused to even boot.

**Steps To Reproduce**
Install latest plugin and boot

**Expected behavior**
Normal plugin load

**Minecraft Server Version**
1.16.5 java 17

**Auto-Tune-Version**
0.14.0 latest

**Additional context**
Error:
`[19:50:51 ERROR]: Error occurred while enabling Auto-Tune v0.14.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at unprotesting.com.github.util.Format.loadLocale(Format.java:53) ~[?:?]
        at unprotesting.com.github.config.Config.<init>(Config.java:135) ~[?:?]
        at unprotesting.com.github.config.Config.initializeConfig(Config.java:84) ~[?:?]
        at unprotesting.com.github.config.Config.init(Config.java:74) ~[?:?]
        at unprotesting.com.github.AutoTune.onEnable(AutoTune.java:35) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more
[19:50:51 INFO]: [Auto-Tune] Disabling Auto-Tune v0.14.0`

**Comment by Unprotesting** [comment]
Yeah there still seems to be a problem loading Auto-Tune on 1.16 and below. Are you using this latest build: https://github.com/Unprotesting/Auto-Tune/actions/runs/2955418360 or the version in the releases tab?
